=== ksm145/Datovy-model-a-API/Data a API by dumbass/API/json-schema/performer_by_id.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Single Performer Schema",
  "type": "object",
  "properties": {
    "id": { "type": "integer" },
    "name": { "type": "string" },
    "company": { "type": "string" },
    "category": { "type": "string" },
    "website": { "type": "string" }
  },
  "required": ["id", "name", "company", "category", "website"]
}

=== ksm145/Datovy-model-a-API/Data a API by dumbass/API/json/performers.json
[
  {
    "id": 1,
    "name": "Linux Foundation",
    "company": "Linux Foundation",
    "category": "Software",
    "website": "https://www.linuxfoundation.org"
  },
  {
    "id": 2,
    "name": "Nextcloud",
    "company": "Nextcloud GmbH",
    "category": "Software",
    "website": "https://nextcloud.com"
  }
]
